# Generated by Django 5.0.6 on 2024-06-13 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('active', models.BooleanField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitoken.emailmodel')),
            ],
        ),
    ]
